[package]
name = "packet_parser"
version = "0.1.0"
edition = "2021"
authors = ["Joonas Bj√∂rk"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun-tap = "0.1.2"